import { applyUuid } from '@steklo24/utils';
import type { GalleryProps } from '@/shared/ui';

export const data: GalleryProps['data'] = [
  {
    c: {
      slug: 'mirrors',
      title: 'Зеркала',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/mirrors/01.jpg',
        th: '/static/images/content/gallery/mirrors/01-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-02. Зеркало с полировкой, наклейка к поверхности стены.',
      },
      {
        im: '/static/images/content/gallery/mirrors/02.jpg',
        th: '/static/images/content/gallery/mirrors/02-thumb.jpg',
        t: 'Напольное зеркало',
        d: 'ЗР-03. Напольное зеркало в багете из нержавеющей стали /900*2500мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/03.jpg',
        th: '/static/images/content/gallery/mirrors/03-thumb.jpg',
        t: 'Напольное зеркало',
        d: 'ЗР-04. Напольное зеркало на основе из крашеного/прозрачного стекла /900*2500мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/04.jpg',
        th: '/static/images/content/gallery/mirrors/04-thumb.jpg',
        t: 'Зеркальные часы',
        d: 'ЗР-07. Зеркальны часы /500*650мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/05.jpg',
        th: '/static/images/content/gallery/mirrors/05-thumb.jpg',
        t: 'Подвесное зеркало',
        d: 'ЗР-09. Круглое подвесное зеркало с матовыми полосами со стороны амальгамы /700мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/06.jpg',
        th: '/static/images/content/gallery/mirrors/06-thumb.jpg',
        t: 'Зеркало с фацетом',
        d: 'ЗР-11. Зеркало с фацетом 30мм /1800*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/07.jpg',
        th: '/static/images/content/gallery/mirrors/07-thumb.jpg',
        t: 'Зеркало в багете',
        d: 'ЗР-12. Зеркало в тонком багете из нержавейки /1600*1600мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/08.jpg',
        th: '/static/images/content/gallery/mirrors/08-thumb.jpg',
        t: 'Зеркальные панели',
        d: 'ЗР-13. Зеркальные панели с полировкой, наклейка к поверхности стены.',
      },
      {
        im: '/static/images/content/gallery/mirrors/09.jpg',
        th: '/static/images/content/gallery/mirrors/09-thumb.jpg',
        t: 'Зеркало в багете',
        d: 'ЗР-14. Зеркало в багете из полированной нержавейки /2800*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/10.jpg',
        th: '/static/images/content/gallery/mirrors/10-thumb.jpg',
        t: 'Зеркальные панели',
        d: 'ЗР-16. Зеркало вклеенное в толщину плитки /1000*2900мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/11.jpg',
        th: '/static/images/content/gallery/mirrors/11-thumb.jpg',
        t: 'Подвесное зеркало',
        d: 'ЗР-18. Подвесные зеркала /600*1500мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/12.jpg',
        th: '/static/images/content/gallery/mirrors/12-thumb.jpg',
        t: 'Зеркальные панели',
        d: 'ЗР-19. Зеркальная панель с полировкой.',
      },
      {
        im: '/static/images/content/gallery/mirrors/13.jpg',
        th: '/static/images/content/gallery/mirrors/13-thumb.jpg',
        t: 'Подвесное зеркало',
        d: 'ЗР-20. Подвесное зеркало над умывальником /1300*1300мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/14.jpg',
        th: '/static/images/content/gallery/mirrors/14-thumb.jpg',
        t: 'Напольное зеркало',
        d: 'ЗР-21. Напольное зеркало в деревянной раме /2400*2800мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/15.jpg',
        th: '/static/images/content/gallery/mirrors/15-thumb.jpg',
        t: 'Подвесное зеркало',
        d: 'ЗР-23. Подвесное зеркало со светильниками /900*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/16.jpg',
        th: '/static/images/content/gallery/mirrors/16-thumb.jpg',
        t: 'Подвесное зеркало',
        d: 'ЗР-24. Подвесное зеркало с полировкой /800*3200мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/17.jpg',
        th: '/static/images/content/gallery/mirrors/17-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-25. Зеркало с полировкой в нише /900*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/18.jpg',
        th: '/static/images/content/gallery/mirrors/18-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-26. Зеркало с полировкой, наклейка к поверхности стены.',
      },
      {
        im: '/static/images/content/gallery/mirrors/19.jpg',
        th: '/static/images/content/gallery/mirrors/19-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-27. Зеркала с полировкой в нишах /700*3200мм/.',
      },
      {
        im: '/static/images/content/gallery/mirrors/20.jpg',
        th: '/static/images/content/gallery/mirrors/20-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-28. Зеркало с полировкой на колонне.',
      },
      {
        im: '/static/images/content/gallery/mirrors/21.jpg',
        th: '/static/images/content/gallery/mirrors/21-thumb.jpg',
        t: 'Тонированное зеркало',
        d: 'ЗР-29. Колонна облицованная серым тонированным зеркалом.',
      },
      {
        im: '/static/images/content/gallery/mirrors/22.jpg',
        th: '/static/images/content/gallery/mirrors/22-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-31. Зеркало с полировкой, наклейка к поверхности стены.',
      },
      {
        im: '/static/images/content/gallery/mirrors/23.jpg',
        th: '/static/images/content/gallery/mirrors/23-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-33. Зеркало с полировкой, наклейка к поверхности стены.',
      },
      {
        im: '/static/images/content/gallery/mirrors/24.jpg',
        th: '/static/images/content/gallery/mirrors/24-thumb.jpg',
        t: 'Зеркало с полировкой',
        d: 'ЗР-34. Зеркало с полировкой, наклейка к поверхности стены.',
      },
    ]),
  },
  {
    c: {
      slug: 'doors',
      title: 'Двери',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/doors/01.jpg',
        th: '/static/images/content/gallery/doors/01-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-03. Откатная дверь с фотопечатью /950*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/02.jpg',
        th: '/static/images/content/gallery/doors/02-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-04. Откатная дверь с фотопечатью /950*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/03.jpg',
        th: '/static/images/content/gallery/doors/03-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-05. Откатная дверь с фотопечатью /950*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/04.jpg',
        th: '/static/images/content/gallery/doors/04-thumb.jpg',
        t: 'Распашная дверь',
        d: 'МД-06. Матовая распашная дверь /800*2000мм/./шт.',
      },
      {
        im: '/static/images/content/gallery/doors/05.jpg',
        th: '/static/images/content/gallery/doors/05-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-07. Матовые откатные двери /1400*2500мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/06.jpg',
        th: '/static/images/content/gallery/doors/06-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-08. Откатная дверь с матовым узором  /950*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/07.jpg',
        th: '/static/images/content/gallery/doors/07-thumb.jpg',
        t: 'Маятниковая дверь',
        d: 'МД-09. Маятниковая матовая дверь /950*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/08.jpg',
        th: '/static/images/content/gallery/doors/08-thumb.jpg',
        t: 'Распашная дверь',
        d: 'МД-10. Распашная матовая дверь с покраской (узор) /900*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/09.jpg',
        th: '/static/images/content/gallery/doors/09-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-12. Откатные матовые двери с фотопечатью /600*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/10.jpg',
        th: '/static/images/content/gallery/doors/10-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-13. Откатная дверь - чёрная тонировка  /1000*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/11.jpg',
        th: '/static/images/content/gallery/doors/11-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-15. Откатная дверь с выборочной покраской  /750*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/11.jpg',
        th: '/static/images/content/gallery/doors/11-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-20. Откатная матовая дверь с фотопечатью /900*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/12.jpg',
        th: '/static/images/content/gallery/doors/12-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-22. Откатные зеркальные двери с фотопечатью /950*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/13.jpg',
        th: '/static/images/content/gallery/doors/13-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-25. Откатные двери с фотопечатью  /900*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/14.jpg',
        th: '/static/images/content/gallery/doors/14-thumb.jpg',
        t: 'Распашная дверь',
        d: 'МД-31. Распашная дверь с матовым узором /800*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/15.jpg',
        th: '/static/images/content/gallery/doors/15-thumb.jpg',
        t: 'Распашная дверь',
        d: 'МД-32. Распашная дверь с матовым узором /800*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/16.jpg',
        th: '/static/images/content/gallery/doors/16-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-33. Откатная дверь с матовым узором /900*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/17.jpg',
        th: '/static/images/content/gallery/doors/17-thumb.jpg',
        t: 'Распашная дверь',
        d: 'МД-36. Распашные двери с матовым узором /800*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/18.jpg',
        th: '/static/images/content/gallery/doors/18-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-38. Откатная матовая дверь /1000*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/19.jpg',
        th: '/static/images/content/gallery/doors/19-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-40. Откатная дверь с матовым узором /900*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/20.jpg',
        th: '/static/images/content/gallery/doors/20-thumb.jpg',
        t: 'Дверь гармошка',
        d: 'МД-44. Дверь гармошка серое тонированное стекло /1100мм*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/21.jpg',
        th: '/static/images/content/gallery/doors/21-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-47. Распашная дверь цветной триплекс /800*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/22.jpg',
        th: '/static/images/content/gallery/doors/22-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-48. Откатная дверь цветной триплекс /850*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/doors/23.jpg',
        th: '/static/images/content/gallery/doors/23-thumb.jpg',
        t: 'Откатная дверь',
        d: 'МД-49. Откатная чёрная тонированная дверь с матовым узором /1000*2100мм/.',
      },
    ]),
  },
  {
    c: {
      slug: 'fences',
      title: 'Ограждения',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/fences/01.jpg',
        th: '/static/images/content/gallery/fences/01-thumb.jpg',
        t: 'Ограждение с деревянным поручнем',
        d: 'ОС-02. Ограждение с деревянным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/02.jpg',
        th: '/static/images/content/gallery/fences/02-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-03. Ограждение со стальным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/03.jpg',
        th: '/static/images/content/gallery/fences/03-thumb.jpg',
        t: 'Перегородка лестничная',
        d: 'ОС-04. Перегородка с поручнем ограждающая лестничный спуск./п.м.',
      },
      {
        im: '/static/images/content/gallery/fences/04.jpg',
        th: '/static/images/content/gallery/fences/04-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-05. Ограждение со стальным поручнем с креплением в торец перекрытия на точечных крепежах.',
      },
      {
        im: '/static/images/content/gallery/fences/05.jpg',
        th: '/static/images/content/gallery/fences/05-thumb.jpg',
        t: 'Стеклянные ступени',
        d: 'ОС-06. Стеклянные ступени из прозрачного закалённого триплекса 8+8+8мм.',
      },
      {
        im: '/static/images/content/gallery/fences/06.jpg',
        th: '/static/images/content/gallery/fences/06-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-07. Ограждение со стальным поручнем с креплением в торец перекрытия на точечных крепежах.',
      },
      {
        im: '/static/images/content/gallery/fences/07.jpg',
        th: '/static/images/content/gallery/fences/07-thumb.jpg',
        t: 'Перегородка лестничная',
        d: 'ОС-08. Перегородка ограждающая лестничный спуск - стекло с фотопечатью./п.м.',
      },
      {
        im: '/static/images/content/gallery/fences/08.jpg',
        th: '/static/images/content/gallery/fences/08-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-11. Ограждение со стальным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/09.jpg',
        th: '/static/images/content/gallery/fences/09-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-12. Самонесущее ограждение вмонтированное в перекрытие.',
      },
      {
        im: '/static/images/content/gallery/fences/10.jpg',
        th: '/static/images/content/gallery/fences/10-thumb.jpg',
        t: 'Ограждение на стойках',
        d: 'ОС-13. Ограждение на стойках с креплением в поверхность парапета.',
      },
      {
        im: '/static/images/content/gallery/fences/11.jpg',
        th: '/static/images/content/gallery/fences/11-thumb.jpg',
        t: 'Ограждение с деревянным поручнем',
        d: 'ОС-15. Ограждение с деревянным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/12.jpg',
        th: '/static/images/content/gallery/fences/12-thumb.jpg',
        t: 'Ограждение на стойках',
        d: 'ОС-16. Ограждение со стальным поручнем на стойках с креплением на перекрытие.',
      },
      {
        im: '/static/images/content/gallery/fences/13.jpg',
        th: '/static/images/content/gallery/fences/13-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-17. Самонесущее ограждение смонтированное в толщину перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/14.jpg',
        th: '/static/images/content/gallery/fences/14-thumb.jpg',
        t: 'Ограждение на стойках',
        d: 'ОС-18. Ограждение со стальным поручнем на стойках с креплением на ступени.',
      },
      {
        im: '/static/images/content/gallery/fences/15.jpg',
        th: '/static/images/content/gallery/fences/15-thumb.jpg',
        t: 'Ограждение на опорном профиле',
        d: 'ОС-19. Ограждение на опорном профиле с стальным поручнем.',
      },
      {
        im: '/static/images/content/gallery/fences/16.jpg',
        th: '/static/images/content/gallery/fences/16-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-20. Самонесущее ограждение с креплением в торец перекрытия на точечных крепежах.',
      },
      {
        im: '/static/images/content/gallery/fences/17.jpg',
        th: '/static/images/content/gallery/fences/17-thumb.jpg',
        t: 'Ограждение с деревянным поручнем',
        d: 'ОС-21. Ограждение с деревянным поручнем вмонтированное в тетиву.',
      },
      {
        im: '/static/images/content/gallery/fences/18.jpg',
        th: '/static/images/content/gallery/fences/18-thumb.jpg',
        t: 'Ограждение на стойках',
        d: 'ОС-22. Ограждение со стальным поручнем на стойках с креплением в торец ступени.',
      },
      {
        im: '/static/images/content/gallery/fences/19.jpg',
        th: '/static/images/content/gallery/fences/19-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-29. Самонесущее ограждение с креплением в торец перекрытия на точечных крепежах.',
      },
      {
        im: '/static/images/content/gallery/fences/20.jpg',
        th: '/static/images/content/gallery/fences/20-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-30. Ограждение со стальным поручнем с креплением в торец перекрытия на точечных крепежах.',
      },
      {
        im: '/static/images/content/gallery/fences/21.jpg',
        th: '/static/images/content/gallery/fences/21-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-31. Ограждение со стальным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/22.jpg',
        th: '/static/images/content/gallery/fences/22-thumb.jpg',
        t: 'Ограждение со стальным поручнем',
        d: 'ОС-32. Ограждение с деревянным поручнем с креплением в торец перекрытия.',
      },
      {
        im: '/static/images/content/gallery/fences/23.jpg',
        th: '/static/images/content/gallery/fences/23-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-34. Самонесущее ограждение с креплением в торец ступеней.',
      },
      {
        im: '/static/images/content/gallery/fences/24.jpg',
        th: '/static/images/content/gallery/fences/24-thumb.jpg',
        t: 'Ограждение самонесущее',
        d: 'ОС-35. Самонесущее ограждение с деревянным поручнем, крепление в торец ступеней.',
      },
    ]),
  },
  {
    c: {
      slug: 'showers',
      title: 'Душевые кабины',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/showers/01.jpg',
        th: '/static/images/content/gallery/showers/01-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-01. Угловая перегородка с откатной дверью с фотопечатью /800-2000*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/02.jpg',
        th: '/static/images/content/gallery/showers/02-thumb.jpg',
        t: 'Дверь с добором',
        d: 'ДП-02. Прозрачная распашная дверь и добор /200-600*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/03.jpg',
        th: '/static/images/content/gallery/showers/03-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-03. Угловая перегородка - прозрачное стекло с фотопечатью /1600-800*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/04.jpg',
        th: '/static/images/content/gallery/showers/04-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-04. Угловая душевая с распашной дверью и фрамугой /1000-2000*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/05.jpg',
        th: '/static/images/content/gallery/showers/05-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-04. Угловая душевая с распашной дверью и фрамугой /1000-2000*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/06.jpg',
        th: '/static/images/content/gallery/showers/06-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-04. Угловая душевая с распашной дверью и фрамугой /1000-2000*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/07.jpg',
        th: '/static/images/content/gallery/showers/07-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-04. Угловая душевая с распашной дверью и фрамугой /1000-2000*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/08.jpg',
        th: '/static/images/content/gallery/showers/08-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-04. Угловая душевая с распашной дверью и фрамугой /1000-2000*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/09.jpg',
        th: '/static/images/content/gallery/showers/09-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-09. Угловая перегородка из синего стекла с распашной дверью /900-1300*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/10.jpg',
        th: '/static/images/content/gallery/showers/10-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-10. Угловая перегородка с распашной дверью /900-1200*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/11.jpg',
        th: '/static/images/content/gallery/showers/11-thumb.jpg',
        t: 'Прямая душевая',
        d: 'ДП-11. Прямая душевая с маятниковой дверью /1800*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/12.jpg',
        th: '/static/images/content/gallery/showers/12-thumb.jpg',
        t: 'Прямая душевая',
        d: 'ДП-11. Прямая душевая с маятниковой дверью /1800*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/13.jpg',
        th: '/static/images/content/gallery/showers/13-thumb.jpg',
        t: 'Прямая душевая',
        d: 'ДП-11. Прямая душевая с маятниковой дверью /1800*2300мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/14.jpg',
        th: '/static/images/content/gallery/showers/14-thumb.jpg',
        t: 'Т-образная перегородка',
        d: 'ДП-14. Т-образная перегородка, сдвижная дверь с матовым узором /1000-1000*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/15.jpg',
        th: '/static/images/content/gallery/showers/15-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-15. Угловая перегородка с перепадом высоты и распашной дверью /900-1200*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/16.jpg',
        th: '/static/images/content/gallery/showers/16-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-15. Угловая перегородка с перепадом высоты и распашной дверью /900-1200*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/17.jpg',
        th: '/static/images/content/gallery/showers/17-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-17. Угловая перегородка с фрамугой /800-1000*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/18.jpg',
        th: '/static/images/content/gallery/showers/18-thumb.jpg',
        t: 'Прямая душевая',
        d: 'ДП-18. Прямая душевая с маятниковой дверью /600-600*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/19.jpg',
        th: '/static/images/content/gallery/showers/19-thumb.jpg',
        t: 'Душевой экран',
        d: 'ДП-19. Неподвижный прозрачный экран /1100*1900мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/20.jpg',
        th: '/static/images/content/gallery/showers/20-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-20. Угловая перегородка с перепадом высоты и маятниковой дверью /200-900-900*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/21.jpg',
        th: '/static/images/content/gallery/showers/21-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-20. Угловая перегородка с перепадом высоты и маятниковой дверью /200-900-900*2200мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/22.jpg',
        th: '/static/images/content/gallery/showers/22-thumb.jpg',
        t: 'Душевой экран',
        d: 'ДП-22. Неподвижный прозрачный экранс /900*2100мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/23.jpg',
        th: '/static/images/content/gallery/showers/23-thumb.jpg',
        t: 'Душевой экран',
        d: 'ДП-23. Два неподвижных экрана из бронзового стекла /700-900*2000мм/.',
      },
      {
        im: '/static/images/content/gallery/showers/24.jpg',
        th: '/static/images/content/gallery/showers/24-thumb.jpg',
        t: 'Угловая душевая',
        d: 'ДП-24. Угловая перегородка с двумя распашными дверями /500-600-600-200*2000мм/.',
      },
    ]),
  },
  {
    c: {
      slug: 'wall-panels',
      title: 'Стеновые панели',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/wall-panels/01.jpg',
        th: '/static/images/content/gallery/wall-panels/01-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-01. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/02.jpg',
        th: '/static/images/content/gallery/wall-panels/02-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-02. Стеновые панели из крашенных стёкол с подсветкой логотипа.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/03.jpg',
        th: '/static/images/content/gallery/wall-panels/03-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-03. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/04.jpg',
        th: '/static/images/content/gallery/wall-panels/04-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-04. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/05.jpg',
        th: '/static/images/content/gallery/wall-panels/05-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-05. Колонны, облицованные крашенным стеклом.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/06.jpg',
        th: '/static/images/content/gallery/wall-panels/06-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-06. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/07.jpg',
        th: '/static/images/content/gallery/wall-panels/07-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-07. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/08.jpg',
        th: '/static/images/content/gallery/wall-panels/08-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-09. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/09.jpg',
        th: '/static/images/content/gallery/wall-panels/09-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-09. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/10.jpg',
        th: '/static/images/content/gallery/wall-panels/10-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-10. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/11.jpg',
        th: '/static/images/content/gallery/wall-panels/11-thumb.jpg',
        t: 'Стекло с фотопечатью',
        d: 'СП-11. Стеновые панели с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/12.jpg',
        th: '/static/images/content/gallery/wall-panels/12-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-12. Стеновые панели из крашенных стекол и стекол с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/13.jpg',
        th: '/static/images/content/gallery/wall-panels/13-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-14. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/14.jpg',
        th: '/static/images/content/gallery/wall-panels/14-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-14. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/15.jpg',
        th: '/static/images/content/gallery/wall-panels/15-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-15. Колонны, облицованные крашенным стеклом.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/16.jpg',
        th: '/static/images/content/gallery/wall-panels/16-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-16. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/17.jpg',
        th: '/static/images/content/gallery/wall-panels/17-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-17. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/18.jpg',
        th: '/static/images/content/gallery/wall-panels/18-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-17. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/19.jpg',
        th: '/static/images/content/gallery/wall-panels/19-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-17. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/20.jpg',
        th: '/static/images/content/gallery/wall-panels/20-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-17. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/21.jpg',
        th: '/static/images/content/gallery/wall-panels/21-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-21. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/22.jpg',
        th: '/static/images/content/gallery/wall-panels/22-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-22. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/23.jpg',
        th: '/static/images/content/gallery/wall-panels/23-thumb.jpg',
        t: 'Крашенное стекло',
        d: 'СП-23. Стеновые панели из крашенных стёкол.',
      },
      {
        im: '/static/images/content/gallery/wall-panels/24.jpg',
        th: '/static/images/content/gallery/wall-panels/24-thumb.jpg',
        t: 'Стекло с фотопечатью',
        d: 'СП-24. Стеновые панели с фотопечатью.',
      },
    ]),
  },
  {
    c: {
      slug: 'kitchens',
      title: 'Кухонные фартуки',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/kitchens/01.jpg',
        th: '/static/images/content/gallery/kitchens/01-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-02. Фартук из закаленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/02.jpg',
        th: '/static/images/content/gallery/kitchens/02-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-04. Фартук из осветленного крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/03.jpg',
        th: '/static/images/content/gallery/kitchens/03-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-06. Фартук из осветленного закаленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/04.jpg',
        th: '/static/images/content/gallery/kitchens/04-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-07. Фартук из крашенного осветленного закаленного стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/05.jpg',
        th: '/static/images/content/gallery/kitchens/05-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-08. Фартук из крашенного осветленного закаленного стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/06.jpg',
        th: '/static/images/content/gallery/kitchens/06-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-10. Фартук из крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/07.jpg',
        th: '/static/images/content/gallery/kitchens/07-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-12. Фартук из крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/08.jpg',
        th: '/static/images/content/gallery/kitchens/08-thumb.jpg',
        t: 'Фартук из осветленного стекла',
        d: 'СФ-14. Фартук из осветленного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/09.jpg',
        th: '/static/images/content/gallery/kitchens/09-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-16. Фартук из закалённого стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/10.jpg',
        th: '/static/images/content/gallery/kitchens/10-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-17. Фартук из закалённого стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/11.jpg',
        th: '/static/images/content/gallery/kitchens/11-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-18. Фартук из осветленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/12.jpg',
        th: '/static/images/content/gallery/kitchens/12-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-19. Фартук из осветленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/13.jpg',
        th: '/static/images/content/gallery/kitchens/13-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-20. Фартук из крашенного осветленного закаленного стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/14.jpg',
        th: '/static/images/content/gallery/kitchens/14-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-22. Фартук из закалённого стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/15.jpg',
        th: '/static/images/content/gallery/kitchens/15-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-24. Фартук из крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/16.jpg',
        th: '/static/images/content/gallery/kitchens/16-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-25. Фартук из крашенного осветленного закаленного стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/17.jpg',
        th: '/static/images/content/gallery/kitchens/17-thumb.jpg',
        t: 'Зеркальный фартук',
        d: 'СФ-26. Фартук из состаренных зеркал.',
      },
      {
        im: '/static/images/content/gallery/kitchens/18.jpg',
        th: '/static/images/content/gallery/kitchens/18-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-29. Фартук из осветленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/19.jpg',
        th: '/static/images/content/gallery/kitchens/19-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-30. Фартук из осветленного стекла с фотопечатью с подсветкой.',
      },
      {
        im: '/static/images/content/gallery/kitchens/20.jpg',
        th: '/static/images/content/gallery/kitchens/20-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-31. Фартук из крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/21.jpg',
        th: '/static/images/content/gallery/kitchens/21-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-33. Фартук из осветленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/22.jpg',
        th: '/static/images/content/gallery/kitchens/22-thumb.jpg',
        t: 'Фартук из крашенного стекла',
        d: 'СФ-36. Фартук и столешница из крашенного закалённого стекла.',
      },
      {
        im: '/static/images/content/gallery/kitchens/23.jpg',
        th: '/static/images/content/gallery/kitchens/23-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-39. Фартук из осветленного стекла с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/kitchens/24.jpg',
        th: '/static/images/content/gallery/kitchens/24-thumb.jpg',
        t: 'Фартук с фотопечатью',
        d: 'СФ-40. Фартук из осветленного стекла с фотопечатью.',
      },
    ]),
  },
  {
    c: {
      slug: 'furniture',
      title: 'Мебель',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/furniture/01.jpg',
        th: '/static/images/content/gallery/furniture/01-thumb.jpg',
        t: 'Тумба стеклянная',
        d: 'СМ-01. Тумбы из осветлённого и чёрного/белого стекла на уф-склейке 400*400*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/02.jpg',
        th: '/static/images/content/gallery/furniture/02-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-02. Стол стеклянный овальный с металлическим подстольем 700*2100*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/03.jpg',
        th: '/static/images/content/gallery/furniture/03-thumb.jpg',
        t: 'Подиум стеклянный',
        d: 'СМ-03. Подиум из чёрного стекла с уф-склейкой 400*400*100мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/04.jpg',
        th: '/static/images/content/gallery/furniture/04-thumb.jpg',
        t: 'Мебельный фасад',
        d: 'СМ-04. Стеклянные фасады из матового стекла с матовым узором 500*700мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/05.jpg',
        th: '/static/images/content/gallery/furniture/05-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-05. Стол стеклянный квадратный с металлическим подстольем 800*800*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/06.jpg',
        th: '/static/images/content/gallery/furniture/06-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-06. Стол стеклянный круглый с фотопечатью на металлическом каркасе 1200*400мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/07.jpg',
        th: '/static/images/content/gallery/furniture/07-thumb.jpg',
        t: 'Тумба стеклянная',
        d: 'СМ-07. Тумбы из осветлённого и белого стекла на уф-склейке 700*1000*300мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/08.jpg',
        th: '/static/images/content/gallery/furniture/08-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-08. Стол стеклянный круглый на металлическом подстолье 1300*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/09.jpg',
        th: '/static/images/content/gallery/furniture/09-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-09. Стол стеклянный овальный на металлическом подстолье 1000*2000*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/10.jpg',
        th: '/static/images/content/gallery/furniture/10-thumb.jpg',
        t: 'Мебельный фасад',
        d: 'СМ-10. Стеклянные фасады из крашенного стекла.',
      },
      {
        im: '/static/images/content/gallery/furniture/11.jpg',
        th: '/static/images/content/gallery/furniture/11-thumb.jpg',
        t: 'Стеклянная витрина',
        d: 'СМ-11. Витрина из осветлённого стекла на уф-склейке 1400*600*200мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/12.jpg',
        th: '/static/images/content/gallery/furniture/12-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-12. Стол стеклянный овальный с фотопечатью на металлическом каркасе 1000*2200*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/13.jpg',
        th: '/static/images/content/gallery/furniture/13-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-13. Стеклянный стол из чёрного стекла и прозрачной столешницы 800*1300*1000мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/14.jpg',
        th: '/static/images/content/gallery/furniture/14-thumb.jpg',
        t: 'Стеклянная полка',
        d: 'СМ-14. Стеклянная прямоугольная полка со скруглёнными углами 600*150мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/15.jpg',
        th: '/static/images/content/gallery/furniture/15-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-15. Стеклянный стол на подстольях из стеклянных фрагментах на уф-склейке 800*2200*900мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/16.jpg',
        th: '/static/images/content/gallery/furniture/16-thumb.jpg',
        t: 'Стол стеклянный',
        d: 'СМ-16. Стол со столешницей из битого триплекса 8+8+8мм с кованным подстольем 1000*2000*800мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/17.jpg',
        th: '/static/images/content/gallery/furniture/17-thumb.jpg',
        t: 'Стеклянная витрина',
        d: 'СМ-17. Открытая стеклянная витрина из прозрачного, матового и белого стекла./п.м.',
      },
      {
        im: '/static/images/content/gallery/furniture/18.jpg',
        th: '/static/images/content/gallery/furniture/18-thumb.jpg',
        t: 'Мебельный фасад',
        d: 'СМ-18. Фасад стойки рецепш из чёрного крашенного стекла 900*2400мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/19.jpg',
        th: '/static/images/content/gallery/furniture/19-thumb.jpg',
        t: 'Стеклянная полка',
        d: 'СМ-19. Полка угловая радиусная из прозрачного стекла 6мм с полкодержателями 300*300мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/20.jpg',
        th: '/static/images/content/gallery/furniture/20-thumb.jpg',
        t: 'Стеклянная полка',
        d: 'СМ-20. Полка прямоугольная с кубическими полкодержателями 900*200мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/21.jpg',
        th: '/static/images/content/gallery/furniture/21-thumb.jpg',
        t: 'Стеклянная витрина',
        d: 'СМ-21. Витрины из прозрачного стекла на уф-склейке.',
      },
      {
        im: '/static/images/content/gallery/furniture/22.jpg',
        th: '/static/images/content/gallery/furniture/22-thumb.jpg',
        t: 'Стеклянная витрина',
        d: 'СМ-22. Витрины из прозрачного стекла на уф-склейке.',
      },
      {
        im: '/static/images/content/gallery/furniture/23.jpg',
        th: '/static/images/content/gallery/furniture/23-thumb.jpg',
        t: 'Подиум стеклянный',
        d: 'СМ-23. Подиум из крашенного стекла с уф-склейкой 600*400*1000мм.',
      },
      {
        im: '/static/images/content/gallery/furniture/24.jpg',
        th: '/static/images/content/gallery/furniture/24-thumb.jpg',
        t: 'Стеклянная витрина',
        d: 'СМ-24. Витрины из прозрачного стекла на уф-склейке.',
      },
    ]),
  },
  {
    c: {
      slug: 'septa',
      title: 'Перегородки',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/septa/01.jpg',
        th: '/static/images/content/gallery/septa/01-thumb.jpg',
        t: 'Перегородка с раздвижными дверями',
        d: 'ПС-01. Перегородка в п-образном профиле с двумя раздвижными дверями.',
      },
      {
        im: '/static/images/content/gallery/septa/02.jpg',
        th: '/static/images/content/gallery/septa/02-thumb.jpg',
        t: 'Перегородка из тонированного стекла',
        d: 'ПС-02. Перегородка из тонированного чёрного стекла.',
      },
      {
        im: '/static/images/content/gallery/septa/03.jpg',
        th: '/static/images/content/gallery/septa/03-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-03. Перегородка в зажимном профиле с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/04.jpg',
        th: '/static/images/content/gallery/septa/04-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-04. Перегородка в зажимном профиле с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/05.jpg',
        th: '/static/images/content/gallery/septa/05-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-05. Перегородка из матовых стёкол с узором с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/06.jpg',
        th: '/static/images/content/gallery/septa/06-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-06. Перегородка из матовых стёкол с узором в широком зажимном профиле.',
      },
      {
        im: '/static/images/content/gallery/septa/07.jpg',
        th: '/static/images/content/gallery/septa/07-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-07. Перегородка в п-образном профиле с матовыми полосами.',
      },
      {
        im: '/static/images/content/gallery/septa/08.jpg',
        th: '/static/images/content/gallery/septa/08-thumb.jpg',
        t: 'Перегородка с откатной дверью',
        d: 'ПС-08. Перегородка в зажимном профиле с раздвижной дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/09.jpg',
        th: '/static/images/content/gallery/septa/09-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-09. Перегородка в монтажом в пазы, с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/10.jpg',
        th: '/static/images/content/gallery/septa/10-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-10. Перегородка в зажимном профиле с матовыми полосами.',
      },
      {
        im: '/static/images/content/gallery/septa/11.jpg',
        th: '/static/images/content/gallery/septa/11-thumb.jpg',
        t: 'Перегородка с откатной дверью',
        d: 'ПС-11. Перегородка в монтажом в пазы, с раздвижной дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/12.jpg',
        th: '/static/images/content/gallery/septa/12-thumb.jpg',
        t: 'Перегородка из зеркального триплекса',
        d: 'ПС-12. Перегородка из зеркального триплекса с фотопечатью.',
      },
      {
        im: '/static/images/content/gallery/septa/13.jpg',
        th: '/static/images/content/gallery/septa/13-thumb.jpg',
        t: 'Перегородка с откатной дверью',
        d: 'ПС-13. Перегородка с двумя раздвижными дверями.',
      },
      {
        im: '/static/images/content/gallery/septa/14.jpg',
        th: '/static/images/content/gallery/septa/14-thumb.jpg',
        t: 'Перегородка с двойным остеклением',
        d: 'ПС-14. Перегородка в профильной системе с двойным остеклением.',
      },
      {
        im: '/static/images/content/gallery/septa/15.jpg',
        th: '/static/images/content/gallery/septa/15-thumb.jpg',
        t: 'Цельностеклянная перегородка',
        d: 'ПС-15. Цельностеклянные перегородки с дверями в алюминиевой раме.',
      },
      {
        im: '/static/images/content/gallery/septa/16.jpg',
        th: '/static/images/content/gallery/septa/16-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-16. Цельностеклянная перегородка с матированием.',
      },
      {
        im: '/static/images/content/gallery/septa/17.jpg',
        th: '/static/images/content/gallery/septa/17-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-17. Цельностеклянная перегородка с матированием.',
      },
      {
        im: '/static/images/content/gallery/septa/18.jpg',
        th: '/static/images/content/gallery/septa/18-thumb.jpg',
        t: 'Перегородка с откатной дверью',
        d: 'ПС-18. Перегородка с дверями на подвесной откатной системе с матированием.',
      },
      {
        im: '/static/images/content/gallery/septa/19.jpg',
        th: '/static/images/content/gallery/septa/19-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-19. Перегородка в зажимном профиле с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/20.jpg',
        th: '/static/images/content/gallery/septa/20-thumb.jpg',
        t: 'Цельностеклянная перегородка',
        d: 'ПС-20. Перегородка в п-образном профиле.',
      },
      {
        im: '/static/images/content/gallery/septa/21.jpg',
        th: '/static/images/content/gallery/septa/21-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-21. Перегородка из матовых стёкол с маятниковой дверью.',
      },
      {
        im: '/static/images/content/gallery/septa/22.jpg',
        th: '/static/images/content/gallery/septa/22-thumb.jpg',
        t: 'Перегородка с маятниковой дверью',
        d: 'ПС-22. Перегородка в зажимном профиле с двумя маятниковыми дверями.',
      },
      {
        im: '/static/images/content/gallery/septa/23.jpg',
        th: '/static/images/content/gallery/septa/23-thumb.jpg',
        t: 'Перегородка с откатной дверью',
        d: 'ПС-23. Перегородка с дверями на подвесной откатной системе с матированием.',
      },
      {
        im: '/static/images/content/gallery/septa/24.jpg',
        th: '/static/images/content/gallery/septa/24-thumb.jpg',
        t: 'Перегородка с матированием',
        d: 'ПС-24. Перегородка в зажимном профиле с матированием.',
      },
    ]),
  },
  {
    c: {
      slug: 'panel',
      title: 'Панно',
    },
    i: applyUuid([
      {
        im: '/static/images/content/gallery/panel/01.jpg',
        th: '/static/images/content/gallery/panel/01-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-01. Зеркальное панно из прямоугольников 300*100мм с полированной кромкой.',
      },
      {
        im: '/static/images/content/gallery/panel/02.jpg',
        th: '/static/images/content/gallery/panel/02-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-03. Зеркальное панно из прямоугольников разных размеров с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/03.jpg',
        th: '/static/images/content/gallery/panel/03-thumb.jpg',
        t: 'Панно из ромбов',
        d: 'ЗП-04. Панно на потолок из ромбов из крашенного стекла с фацетом 10 мм.',
      },
      {
        im: '/static/images/content/gallery/panel/04.jpg',
        th: '/static/images/content/gallery/panel/04-thumb.jpg',
        t: 'Панно из ромбов',
        d: 'ЗП-06. Зеркальное панно из ромбов 600*400мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/05.jpg',
        th: '/static/images/content/gallery/panel/05-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-07. Зеркальное панно из прямоугольников 300*100мм с полированной кромкой.',
      },
      {
        im: '/static/images/content/gallery/panel/06.jpg',
        th: '/static/images/content/gallery/panel/06-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-08. Панно из зеркал прямоугольной формы с фацетом 20мм.',
      },
      {
        im: '/static/images/content/gallery/panel/07.jpg',
        th: '/static/images/content/gallery/panel/07-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-10. Зеркальной панно из квадратов 150*150мм с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/08.jpg',
        th: '/static/images/content/gallery/panel/08-thumb.jpg',
        t: 'Панно из ромбов',
        d: 'ЗП-11. Зеркальное панно из ромбов 300*200мм с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/09.jpg',
        th: '/static/images/content/gallery/panel/09-thumb.jpg',
        t: 'Панно геометрия',
        d: 'ЗП-17. Зеркальное панно из разных геометрических фигур с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/10.jpg',
        th: '/static/images/content/gallery/panel/10-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-21. Зеркальное панно из квадратов 120*120мм с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/11.jpg',
        th: '/static/images/content/gallery/panel/11-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-22. Зеркальное панно из квадратов 300*300мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/12.jpg',
        th: '/static/images/content/gallery/panel/12-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-26. Зеркальное панно из квадратов 250*250мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/13.jpg',
        th: '/static/images/content/gallery/panel/13-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-27. Зеркальное панно из квадратов 300*300мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/14.jpg',
        th: '/static/images/content/gallery/panel/14-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-28. Зеркальное панно из квадратов 300*300мм с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/15.jpg',
        th: '/static/images/content/gallery/panel/15-thumb.jpg',
        t: 'Панно геометрия',
        d: 'ЗП-30. Зеркальное панно из разных геометрических фигур с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/16.jpg',
        th: '/static/images/content/gallery/panel/16-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-32. Зеркальное панно из квадратов 400*400мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/17.jpg',
        th: '/static/images/content/gallery/panel/17-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-33. Зеркальное панно из квадратов 400*400мм со вставками из зеркала бронзы.',
      },
      {
        im: '/static/images/content/gallery/panel/18.jpg',
        th: '/static/images/content/gallery/panel/18-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-34. Зеркальное панно из квадратов 500*500мм с фацетом 10мм.',
      },
      {
        im: '/static/images/content/gallery/panel/19.jpg',
        th: '/static/images/content/gallery/panel/19-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-35. Зеркальное панно из прямоугольников с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/20.jpg',
        th: '/static/images/content/gallery/panel/20-thumb.jpg',
        t: 'Панно из квадратов',
        d: 'ЗП-36. Зеркальное панно из квадратов 400*400мм с фацетом 15мм.',
      },
      {
        im: '/static/images/content/gallery/panel/21.jpg',
        th: '/static/images/content/gallery/panel/21-thumb.jpg',
        t: 'Зеркало в обрамлении',
        d: 'ЗП-39. Зеркало 1500*1100мм, обрамленное прямоугольниками с фацетом 30мм.',
      },
      {
        im: '/static/images/content/gallery/panel/22.jpg',
        th: '/static/images/content/gallery/panel/22-thumb.jpg',
        t: 'Панно из ромбов',
        d: 'ЗП-40. Зеркальное панно из ромбов 600*300мм с фацетом 25мм.',
      },
      {
        im: '/static/images/content/gallery/panel/23.jpg',
        th: '/static/images/content/gallery/panel/23-thumb.jpg',
        t: 'Панно из прямоугольников',
        d: 'ЗП-43. Панно из состаренных зеркал с фацетом 5мм.',
      },
      {
        im: '/static/images/content/gallery/panel/24.jpg',
        th: '/static/images/content/gallery/panel/24-thumb.jpg',
        t: 'Панно геометрия',
        d: 'ЗП-47. Зеркальное панно из разных геометрических фигур с полировкой.',
      },
    ]),
  },
];
